"""added a lot of indexs

Revision ID: fd59ca9eb5c0
Revises: f758afb31e9f
Create Date: 2026-04-10 18:35:48.395973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd59ca9eb5c0'
down_revision: Union[str, Sequence[str], None] = 'f758afb31e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_app_users_email'), 'app_users', type_='unique')
    op.drop_constraint(op.f('uq_app_users_username'), 'app_users', type_='unique')
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=True)
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.create_index(op.f('ix_permissions_permission_slang'), 'permissions', ['permission_slang'], unique=False)
    op.create_index('ix_permission_roles_role_permissions', 'role_permissions', ['role_id', 'permission_id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index('ix_user_roles_role_user', 'user_roles', ['role_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_roles_role_user', table_name='user_roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index('ix_permission_roles_role_permissions', table_name='role_permissions')
    op.drop_index(op.f('ix_permissions_permission_slang'), table_name='permissions')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.create_unique_constraint(op.f('uq_app_users_username'), 'app_users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_app_users_email'), 'app_users', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
